---

name: "${DOCKER_COMPOSE_NAME}"

x-common-labels: &common-labels
  production_status: ${LABELS_PRODUCTION_STATUS}
  network_name: ${LABELS_NETWORK_NAME}
  network_type: ${LABELS_NETWORK_TYPE}
  node_role: ${LABELS_NODE_ROLE}
  node_name: ${LABELS_NODE_NAME}
  sub_system_key: ${LABELS_SUB_SYSTEM_KEY}
  sub_system_name: ${LABELS_SUB_SYSTEM_NAME}

x-logging-settings-fluentd: &logging-settings-fluentd
  logging:
    driver: fluentd
    options:
      # fluentd-address: "${FLUENTD_PROTOCOL}://${FLUENTD_HOST}:${FLUENTD_PORT}" # Logstash UDP input port
      fluentd-address: "${FLUENTD_HOST}:${FLUENTD_PORT}" # Logstash UDP input port
      tag: "${FLUENTD_TAG}"
      labels: "${FLUENTD_LABELS}"
      env: "${FLUENTD_ENV}"

x-logging-settings-gelf: &logging-settings-gelf
  logging:
    driver: gelf
    options:
      gelf-address: "${GRAYLOG_PROTOCOL}://${GRAYLOG_HOST}:${GRAYLOG_PORT}" # Logstash UDP input port
      tag: "${GRAYLOG_TAG}"
      gelf-compression-type: none
      labels: "${GRAYLOG_LABELS}"
      env: "${GRAYLOG_ENV}"

x-logging-settings-local: &logging-settings-local
  logging:
    driver: "local"
    options:
      max-size: "10m"
      max-file: "3"

x-logging-settings-json: &logging-settings-json
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
      labels: "production_status,network_name,network_type"
      env: "os,customer"

x-logging-settings-journald: &logging-settings-journald
  logging:
    driver: "journald"
    options:
      tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
      labels: "production_status,network_name,network_type"
      env: "os,customer"

x-general-settings: &general-settings
  restart: unless-stopped
  stdin_open: true
  tty: true  

services:
  node:
    hostname: "${DOCKER_COMPOSE_NAME}"
    container_name: "${DOCKER_COMPOSE_NAME}"
    image: "${DOCKER_COMPOSE_IMAGE}"
    ports:
      - ${DOCKER_COMPOSE_NETWORK_INTERFACE_ADDRESS}:${PORT_DEFAULT_PUBLISHED}:${PORT_DEFAULT_TARGETED}
    <<: [ *logging-settings-gelf, *general-settings ]
    labels:
      <<: *common-labels
